# Generated by Django 2.2.1 on 2019-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0002_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="conclusion",
            field=models.TextField(blank=True, default=""),
        ),
    ]
