# Generated by Django 2.2.1 on 2019-10-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0005_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(default="", max_length=100)),
                ("ip", models.CharField(default="", max_length=100)),
                ("os", models.CharField(default="", max_length=100)),
                ("notes", models.CharField(default="", max_length=1000)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ptart.Project",
                    ),
                ),
            ],
            options={
                "ordering": ("hostname",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField(default=0)),
                ("protocol", models.CharField(default="", max_length=200)),
                ("name", models.CharField(default="", max_length=200)),
                ("version", models.CharField(default="", max_length=100)),
                ("banner", models.CharField(default="", max_length=1000)),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ptart.Host",
                    ),
                ),
            ],
            options={
                "ordering": ("port",),
            },
        ),
    ]
