# Generated by Django 2.2.8 on 2020-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptart', '0006_host_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='displayable',
            field=models.BooleanField(default=True),
        ),
    ]
