# Generated by Django 2.2.24 on 2022-04-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0010_project_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="deprecated",
            field=models.BooleanField(default=False),
        ),
    ]
