# Generated by Django 3.2.15 on 2023-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptart', '0018_attackscenario_body_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='', max_length=200),
        ),
    ]
