# Generated by Django 3.2.15 on 2023-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptart', '0019_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
