# Generated by Django 3.2.16 on 2023-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptart', '0026_project_methodologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodology',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
