# Generated by Django 3.2.16 on 2023-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptart', '0027_methodology_deprecated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='banner',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
