# Generated by Django 4.2.13 on 2024-07-16 07:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def get_project_creation_event(apps, project):
    """Create the project creation event"""
    Event = apps.get_model('ptart', 'Event')
    return Event.objects.create(
        type='PC',
        title='Project created',
        date=project.added,
        project=project,
        related_id=project.id
    )

def get_assessment_creation_event(apps, assessment):
    """Create the assessment creation event"""
    Event = apps.get_model('ptart', 'Event')
    return Event.objects.create(
            type='AC',
            title='Assessment ' + assessment.name + ' created',
            date=assessment.added,
            project=assessment.project,
            related_id=assessment.id
        )

def get_hit_creation_event(apps, hit):
    """Create the hit creation event"""
    Event = apps.get_model('ptart', 'Event')
    return Event.objects.create(
        type='HC',
        title='Hit ' + "PTART-" + str(hit.added.year) + "-" + str(hit.id).zfill(5) + ' created',
        date=hit.added,
        project=hit.assessment.project,
        related_id=hit.id
    )

def init_events(apps, schema_editor):
    Project = apps.get_model('ptart', 'Project')
    for project in Project.objects.all():
        event = get_project_creation_event(apps, project)
        event.save()
        for assessment in project.assessment_set.all():
            event = get_assessment_creation_event(apps, assessment)
            event.save()
            for hit in assessment.hit_set.all():
                event = get_hit_creation_event(apps, hit)
                event.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptart', '0035_alter_screenshot_options_screenshot_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PC', 'Project Creation'), ('AC', 'Assessment Creation'), ('HC', 'Hit Creation'), ('SC', 'Attack Scenario Creation'), ('RC', 'Recommendation Creation'), ('CC', 'Retest Campaign Creation'), ('TU', 'Retest Hit Update'), ('CE', 'Custom Event')], max_length=2)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('related_id', models.IntegerField(default=-1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptart.project')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.RunPython(init_events),
    ]
