# Generated by Django 4.2.13 on 2024-09-06 15:12

from django.db import migrations, models


def init_hit_status(apps, schema_editor):
    Hit = apps.get_model("ptart", "Hit")
    for hit in Hit.objects.all():
        if hit.displayable:
            hit.status = "V"
        else:
            hit.status = "H"
        hit.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0036_retestscreenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("R", "To Review"),
                    ("F", "To Fix"),
                    ("V", "Validated"),
                    ("H", "Hidden"),
                ],
                default="D",
                max_length=1,
            ),
        ),
        migrations.RunPython(init_hit_status),
    ]
