# Generated by Django 4.2.13 on 2025-01-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptart', '0038_remove_hit_displayable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWEs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('deprecated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CWE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('extended_description', models.TextField(blank=True, default='')),
                ('cwes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ptart.cwes')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
