# Generated by Django 4.2.13 on 2025-01-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0041_project_cwes"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="cwes",
            field=models.ManyToManyField(to="ptart.cwe"),
        ),
    ]
