# Generated by Django 4.2.13 on 2025-06-20 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ptart", "0043_alter_cwes_options_alter_project_cwes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="reviewers",
            field=models.ManyToManyField(
                related_name="%(class)s_reviewers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
