# Generated by Django 2.1.7 on 2019-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='sh0t',
            name='labels',
            field=models.ManyToManyField(to='app.Label'),
        ),
    ]
