# Generated by Django 2.1.7 on 2019-03-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='order',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
