# Generated by Django 2.1.7 on 2019-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flag_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sh0t',
            options={'ordering': ('severity', '-cvss', 'title')},
        ),
        migrations.AddField(
            model_name='flag',
            name='asset',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sh0t',
            name='asset',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='template',
            name='asset',
            field=models.CharField(default='', max_length=256),
        ),
    ]
