# Generated by Django 2.1.7 on 2019-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190305_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='sh0t',
            name='cvss',
            field=models.CharField(default='---', max_length=3),
        ),
    ]
