# Generated by Django 2.1.7 on 2019-04-01 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_project_pentesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(related_name='project_viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pentesters',
            field=models.ManyToManyField(related_name='project_pentesters', to=settings.AUTH_USER_MODEL),
        ),
    ]
