# Generated by Django 2.0.8 on 2019-02-03 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sh0t_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(default="")
        ),
    ]
