# Generated by Django 2.0.8 on 2019-02-03 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='severity',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])
        ),
    ]
