# Generated by Django 2.0.8 on 2019-02-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_template_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sh0t',
            options={'ordering': ('severity', 'title')},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('severity', 'name')},
        ),
    ]
