# Generated by Django 2.0.8 on 2019-02-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_change_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='added',
        ),
    ]
