# Generated by Django 2.1.7 on 2019-02-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_move_configuration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseMaster',
            new_name='Case',
        ),
        migrations.RenameModel(
            old_name='MethodologyMaster',
            new_name='Methodology',
        ),
        migrations.RenameModel(
            old_name='ModuleMaster',
            new_name='Module',
        ),
    ]
