# Generated by Django 3.2.15 on 2023-01-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0020_alter_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="engagement_overview",
            field=models.TextField(blank=True, default=""),
        ),
    ]
