# Generated by Django 3.2.16 on 2023-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0024_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
