# Generated by Django 3.2.16 on 2024-03-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0029_auto_20240314_0353"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cvss",
            new_name="Cvss3",
        ),
    ]
