# Generated by Django 4.2.13 on 2025-01-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0039_cwes_cwe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cwe",
            options={"ordering": ("cwe_id",)},
        ),
    ]
