# Generated by Django 4.2.13 on 2025-03-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ptart", "0042_hit_cwes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cwes",
            options={"ordering": ("version",)},
        ),
        migrations.AlterField(
            model_name="project",
            name="cwes",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="ptart.cwes"
            ),
        ),
    ]
