# Generated by Django 2.1.7 on 2019-04-25 14:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cvss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_vector', models.CharField(choices=[('N', 'Network'), ('A', 'Adjacent'), ('L', 'Local'), ('P', 'Physical')], max_length=1)),
                ('attack_complexity', models.CharField(choices=[('L', 'Low'), ('H', 'High')], max_length=1)),
                ('privilege_required', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('user_interaction', models.CharField(choices=[('N', 'None'), ('R', 'Required')], max_length=1)),
                ('scope', models.CharField(choices=[('U', 'Unchanged'), ('C', 'Changed')], max_length=1)),
                ('confidentiality', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('integrity', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('availability', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('decimal_value', models.DecimalField(decimal_places=1, default=-1.0, max_digits=3)),
            ],
            options={
                'ordering': ('decimal_value',),
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('asset', models.CharField(blank=True, default='', max_length=256)),
                ('done', models.BooleanField(default=False)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sh00t.Assessment')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('methodology', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sh00t.Methodology')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.TextField(blank=True, default='')),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('pentesters', models.ManyToManyField(related_name='project_pentesters', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='project_viewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots')),
            ],
        ),
        migrations.CreateModel(
            name='Sh0t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('asset', models.CharField(blank=True, default='', max_length=256)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('severity', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sh00t.Assessment')),
                ('cvss', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sh00t.Cvss')),
                ('labels', models.ManyToManyField(to='sh00t.Label')),
            ],
            options={
                'ordering': ('severity', '-cvss', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(blank=True, default='')),
                ('asset', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ('severity', 'name'),
            },
        ),
        migrations.AddField(
            model_name='screenshot',
            name='sh0t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sh00t.Sh0t'),
        ),
        migrations.AddField(
            model_name='case',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sh00t.Module'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sh00t.Project'),
        ),
    ]
