# Generated by Django 2.1.7 on 2019-04-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sh00t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_vector', models.CharField(choices=[('N', 'Network'), ('A', 'Adjacent'), ('L', 'Local'), ('P', 'Physical')], max_length=1)),
                ('attack_complexity', models.CharField(choices=[('L', 'Low'), ('H', 'High')], max_length=1)),
                ('privilege_required', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('user_interaction', models.CharField(choices=[('N', 'None'), ('R', 'Required')], max_length=1)),
                ('scope', models.CharField(choices=[('U', 'Unchanged'), ('C', 'Changed')], max_length=1)),
                ('confidentiality', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('integrity', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('availability', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('decimal_value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('string_value', models.CharField(default='---', max_length=4)),
            ],
            options={
                'ordering': ('decimal_value',),
            },
        ),
        migrations.AlterField(
            model_name='sh0t',
            name='cvss',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sh00t.Cvss'),
        ),
    ]
